### ISSUE TITLE
If we modeling a symmetrical model using a mirror and a subdiv, then the outside vertices are not merged in subdiv..

### ISSUE THREAD

**Issue by MarkMironov** [umiyuki/Artstage-Issues#92] opened 2019-12-09 14:26 UTC
This happens in any mesh. Even with the "pin vertices" tick turned on. Internal vertices merge normally.
![Image 2019, 12, 09, 16, 05, 02](https://user-images.githubusercontent.com/55280047/70443150-51f01700-1aa0-11ea-904c-c5d4c25a6af5.png)

**Comment by umiyuki** [comment] 2019-12-09 21:13
It is not a bug. This is also the case with Blender.
![image](https://user-images.githubusercontent.com/6958622/70473198-ee9fcc80-1b13-11ea-83b6-72815d7d723d.png)

**Comment by MarkMironov** [comment] 2019-12-10 08:55
@umiyuki This is because you put the mirror modifier after the subsurf modifier. Swap them, and you will see that the subsurf will merge.

**Comment by umiyuki** [comment] 2019-12-10 13:54
That's true, but it's still not a bug. It just didn't work as you expected.
This is not a big hindrance in production work. If you freeze the mirror at the end of the work, the end vertices will be connected.
And this only happens with open meshes, but in real modeling it usually creates a closed mesh.
You can also connect vertices with Smooth Weight if you really care.

**Comment by MarkMironov** [comment] 2019-12-15 11:38
@umiyuki What do you mean by "Smooth Weight"?
Is this when the edge weight is set to zero? If so, it didn’t help me.

**Comment by umiyuki** [comment] 2019-12-17 02:11
Set the vertex weight to 5.

**Comment by umiyuki** [comment] 2020-01-25 06:13
If there is no progress in the next two months, close this issue.

**Comment by MarkMironov** [comment] 2020-01-25 22:53
@umiyuki 
Your method helped me. True, this is not quite how it should be, but since you don't want to change the behavior of the side vertices, then you can close the topic.

**Comment by umiyuki** [comment] 2020-01-26 16:41
Why leaved the thread after getting the answer and the problem solved? Anyway, close this issue.

**Closed by umiyuki** 2020-01-26 16:41 UTC
Labels: bug
